# Generated by Django 5.1 on 2024-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
