# Generated by Django 5.1 on 2024-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_userstock_unique_user_stock_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
