# Generated by Django 5.1 on 2024-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_userstock_invested_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
