# Generated by Django 5.1 on 2024-08-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_userstock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDataAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('file_name', models.CharField(db_index=True, max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Stock Data Audit',
                'verbose_name_plural': 'Stock Data Audits',
                'db_table': 'stock_data_audit',
                'ordering': ['-id'],
            },
        ),
    ]
